apiVersion: apps/v1
kind: Deployment
metadata:
  name: tublessin-chat
spec:
  replicas: 2
  selector:
    matchLabels:
      name: tublessin-chat
  template:
    metadata:
      name: tublessin-chat
      labels:
        name: tublessin-chat
    spec:
      containers:
        - name: tublessin-chat
          image: gerins/tublessin-chat
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          envFrom:
            - configMapRef:
                name: configmap-chat
            - secretRef:
                name: secret-chat
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    name: tublessin-chat
  ports:
    - port: 5000
      targetPort: 5000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-chat
data:
  GRPC_SERVICE_CHAT_HOST: tcp
  GRPC_SERVICE_CHAT_PORT: "5000"

  REDIS_DATABASE_HOST: redis-service.default.svc.cluster.local
  REDIS_DATABASE_PORT: "6379"
  REDIS_DATABASE_SELECT: "3"

  MYSQL_DB_DRIVER: mysql
  MYSQL_DB_NAME: tublessin_chat
  MYSQL_DB_HOST: db-service.default.svc.cluster.local
  MYSQL_DB_PORT: "3306"

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-chat
stringData:
  REDIS_DATABASE_USERNAME: admin
  REDIS_DATABASE_PASSWORD: redisadmin

  MYSQL_DB_USER: root
  MYSQL_DB_PASSWORD: admin
