apiVersion: apps/v1
kind: Deployment
metadata:
  name: tublessin-gateway
spec:
  selector:
    matchLabels:
      name: tublessin-gateway
  template:
    metadata:
      name: tublessin-gateway
      labels:
        name: tublessin-gateway
    spec:
      containers:
        - name: tublessin-gateway
          image: gerins/tublessin-gateway
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 60m
              memory: 100Mi
          envFrom:
            - configMapRef:
                name: configmap-gateway

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-gateway
spec:
  minReplicas: 2
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tublessin-gateway
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    name: tublessin-gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-gateway
data:
  API_GATEWAY_SERVER_HOST: ""
  API_GATEWAY_SERVER_PORT: "8080"

  SERVICE_LOGIN_HOST: login-service.default.svc.cluster.local
  SERVICE_LOGIN_PORT: "9000"

  SERVICE_TRANSACTION_HOST: transaction-service.default.svc.cluster.local
  SERVICE_TRANSACTION_PORT: "6000"

  SERVICE_MONTIR_HOST: montir-service.default.svc.cluster.local
  SERVICE_MONTIR_PORT: "8000"

  SERVICE_USER_HOST: user-service.default.svc.cluster.local
  SERVICE_USER_PORT: "7000"

  SERVICE_CHAT_HOST: chat-service.default.svc.cluster.local
  SERVICE_CHAT_PORT: "5000"
