apiVersion: apps/v1
kind: Deployment
metadata:
  name: tublessin-montir
spec:
  selector:
    matchLabels:
      name: tublessin-montir
  template:
    metadata:
      name: tublessin-montir
      labels:
        name: tublessin-montir
    spec:
      containers:
        - name: tublessin-montir
          image: gerins/tublessin-montir
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 70m
              memory: 100Mi
          envFrom:
            - configMapRef:
                name: configmap-montir
            - secretRef:
                name: secret-montir

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-montir
spec:
  minReplicas: 2
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tublessin-montir
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70

---
apiVersion: v1
kind: Service
metadata:
  name: montir-service
spec:
  selector:
    name: tublessin-montir
  ports:
    - port: 8000
      targetPort: 8000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-montir
data:
  GRPC_SERVICE_MONTIR_HOST: tcp
  GRPC_SERVICE_MONTIR_PORT: "8000"

  REDIS_DATABASE_HOST: redis-service.default.svc.cluster.local
  REDIS_DATABASE_PORT: "6379"
  REDIS_DATABASE_SELECT: "1"

  MYSQL_DB_DRIVER: mysql
  MYSQL_DB_NAME: tublessin_montir
  MYSQL_DB_HOST: db-service.default.svc.cluster.local
  MYSQL_DB_PORT: "3306"

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-montir
stringData:
  REDIS_DATABASE_USERNAME: admin
  REDIS_DATABASE_PASSWORD: redisadmin

  MYSQL_DB_USER: root
  MYSQL_DB_PASSWORD: admin
