apiVersion: apps/v1
kind: Deployment
metadata:
  name: tublessin-user
spec:
  selector:
    matchLabels:
      name: tublessin-user
  template:
    metadata:
      name: tublessin-user
      labels:
        name: tublessin-user
    spec:
      containers:
        - name: tublessin-user
          image: gerins/tublessin-user
          ports:
            - containerPort: 7000
          resources:
            requests:
              cpu: 40m
              memory: 40Mi
            limits:
              cpu: 50m
              memory: 50Mi
          envFrom:
            - configMapRef:
                name: configmap-user
            - secretRef:
                name: secret-user

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-user
spec:
  minReplicas: 2
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tublessin-user
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    name: tublessin-user
  ports:
    - port: 7000
      targetPort: 7000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-user
data:
  GRPC_SERVICE_USER_HOST: tcp
  GRPC_SERVICE_USER_PORT: "7000"

  REDIS_DATABASE_HOST: redis-service.default.svc.cluster.local
  REDIS_DATABASE_PORT: "6379"
  REDIS_DATABASE_SELECT: "2"

  MYSQL_DB_DRIVER: mysql
  MYSQL_DB_NAME: tublessin_user
  MYSQL_DB_HOST: db-service.default.svc.cluster.local
  MYSQL_DB_PORT: "3306"

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-user
stringData:
  REDIS_DATABASE_USERNAME: admin
  REDIS_DATABASE_PASSWORD: redisadmin

  MYSQL_DB_USER: root
  MYSQL_DB_PASSWORD: admin
