name: Build and Push to Docker Container Registry

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 
      uses: actions/setup-go@v2

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Compiling Golang App
      run: |
        cd api_gateway
        go build -o tublessin-gateway

    - name: Docker Build
      run: docker build -t gerins/tublessin-gateway .
      
    - name: Push to Docker Hub
      run: docker push gerins/tublessin-gateway
