name: Build and Push to Docker Container Registry

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 
      uses: actions/setup-go@v2

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Compiling api_gateway -> Build Image -> Push Image 
      run: |
        cd api_gateway
        go build -o tublessin-gateway
        docker build -t gerins/tublessin-gateway .
        docker push gerins/tublessin-gateway

    - name: Compiling login_service -> Build Image -> Push Image 
      run: |
        cd services/login_service
        go build -o tublessin-login
        docker build -t gerins/tublessin-login .
        docker push gerins/tublessin-login

    - name: Compiling chat_service -> Build Image -> Push Image 
      run: |
        cd services/chat_service
        go build -o tublessin-chat
        docker build -t gerins/tublessin-chat .
        docker push gerins/tublessin-chat

    - name: Compiling montir_service -> Build Image -> Push Image 
      run: |
        cd services/montir_service
        go build -o tublessin-montir
        docker build -t gerins/tublessin-montir .
        docker push gerins/tublessin-montir

    - name: Compiling user_service -> Build Image -> Push Image 
      run: |
        cd services/user_service
        go build -o tublessin-user
        docker build -t gerins/tublessin-user .
        docker push gerins/tublessin-user

    - name: Compiling transaction_service -> Build Image -> Push Image 
      run: |
        cd services/transaction_service
        go build -o tublessin-transaction
        docker build -t gerins/tublessin-transaction .
        docker push gerins/tublessin-transaction
